version: '3.1'
services:
  openfire:
    build: build/openfire
    image: openfire-dev
    restart: unless-stopped
    ports:
      - "9090:9090/tcp"
      - "9091:9091/tcp"
      - "5222:5222/tcp"
      - "7777:7777/tcp"
      - "7070:7070/tcp"
    ulimits:
      nproc: 409600
      nofile: 819200
    volumes:
      - ./openfire-data:/var/lib/openfire
      - ./logs:/var/log/openfire
    environment:
      TZ: "America/Bogota"
      DAEMON_OPTS: -Xms32m -Xmx128m -Xss128k -Xoss128k -XX:ThreadStackSize=128 -XX:+PrintGCDetails -Xloggc:/var/log/openfire/gc.log -XX:+HeapDumpOnOutOfMemoryError
    links:
      - db:database_srv
    depends_on:
      - db

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      TZ: "America/Bogota"
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: openfire_db
      MYSQL_USER: openfire_db_user
      MYSQL_PASSWORD: s3cr3t
    ports:
      - "3306:3306/tcp"
    
  adminer:
    image: adminer
    restart: unless-stopped
    environment:
      TZ: "America/Bogota"
    ports:
      - 8080:8080
    links:
      - db:database_srv